# Generated by Django 4.0.4 on 2022-04-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name of course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='School of Area')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='Name')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='Gender')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.department', verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='Name')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('gender', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female')], default=1, verbose_name='Gender')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.department', verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('email', models.CharField(help_text='QQ号/微信/手机号', max_length=64, unique=True, verbose_name='')),
                ('phone', models.CharField(help_text='QQ号/微信/手机号', max_length=64, unique=True, verbose_name='')),
                ('status', models.IntegerField(choices=[(1, 'Registered'), (2, 'Not registered')], default=2, verbose_name='状态')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('source', models.SmallIntegerField(choices=[(1, 'Friends'), (2, 'Official Web'), (3, 'Advisement'), (4, 'Others')], default=1, verbose_name='Source')),
                ('course', models.ManyToManyField(to='web.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(verbose_name='Term')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='Finish Date')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='classes', to='web.employee', verbose_name='Class Teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.course', verbose_name='Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.school', verbose_name='School')),
                ('tech_teachers', models.ManyToManyField(blank=True, related_name='teach_classes', to='web.employee', verbose_name='Teacher')),
            ],
        ),
    ]
