# Generated by Django 4.0.4 on 2022-05-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(verbose_name='Day Num')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('class_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.classlist', verbose_name='ClassList')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.employee', verbose_name='Teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=32, verbose_name='COURSE'),
        ),
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Campus'),
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[('normal', 'Normal'), ('vacate', 'On leave'), ('late', 'Be late'), ('absence', 'Absence from work'), ('leave_early', 'Leave early')], default='checked', max_length=64, verbose_name='Record of class')),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.courserecord', verbose_name='Day of the course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Reason')),
                ('score', models.IntegerField(help_text='Disciplinary deduction points, good performance bonus points', verbose_name='Score')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student', verbose_name='Student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.employee', verbose_name='Executor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.IntegerField(choices=[(1, 'registery fee'), (2, 'tuition fee'), (3, 'drop out'), (4, 'others')], default=1, verbose_name='Type')),
                ('paid_fee', models.IntegerField(default=0, verbose_name='Amount')),
                ('apply_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('confirm_status', models.IntegerField(choices=[(1, 'Applying'), (2, 'Confirmed'), (3, 'Rejected')], default=1, verbose_name='Status')),
                ('confirm_date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('class_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.classlist', verbose_name='Class')),
                ('confirm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='web.employee', verbose_name='Approver')),
                ('consultant', models.ForeignKey(help_text='This belongs to who signed the contract', on_delete=django.db.models.deletion.CASCADE, to='web.employee', verbose_name='Consultant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Content')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.employee', verbose_name='Recorder')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer', verbose_name='Customer')),
            ],
        ),
    ]
