# Generated by Django 4.0.4 on 2022-05-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('icon', models.CharField(max_length=32, verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('alias', models.CharField(max_length=64, unique=True, verbose_name='Alias')),
                ('url', models.CharField(max_length=128, verbose_name='URL with RE')),
                ('menu', models.ForeignKey(blank=True, help_text='null means not a menu; non-null means it is a secondary menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='To Menu')),
                ('parent_id', models.ForeignKey(blank=True, help_text='non-menu permissions and menu permissions', max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='rbac.permission', verbose_name='Parent ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('permission', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='rbac.permission', verbose_name='permission')),
            ],
        ),
    ]
